name: medoapi
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'  
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
